//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Protocol_Preprocessor {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Bladdermin_XML_Library")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Bladdermin_XML_Library", IsNullable=false)]
    public partial class BladderminProtocol {
        
        private byte versionField;
        
        private BladderminProtocolProtocolMetaData protocolMetaDataField;
        
        private BladderminProtocolConstraints[] constraintsField;
        
        /// <remarks/>
        public byte version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public BladderminProtocolProtocolMetaData ProtocolMetaData {
            get {
                return this.protocolMetaDataField;
            }
            set {
                this.protocolMetaDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constraints")]
        public BladderminProtocolConstraints[] Constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Bladdermin_XML_Library")]
    public partial class BladderminProtocolProtocolMetaData {
        
        private string nameField;
        
        private bool nodesTreatableField;
        
        private bool multiPhaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool NodesTreatable {
            get {
                return this.nodesTreatableField;
            }
            set {
                this.nodesTreatableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool MultiPhase {
            get {
                return this.multiPhaseField;
            }
            set {
                this.multiPhaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Bladdermin_XML_Library")]
    public partial class BladderminProtocolConstraints {
        
        private BladderminProtocolConstraintsConstraint[] constraintField;
        
        private bool nodesField;
        
        private bool multiPhaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constraint")]
        public BladderminProtocolConstraintsConstraint[] Constraint {
            get {
                return this.constraintField;
            }
            set {
                this.constraintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Nodes {
            get {
                return this.nodesField;
            }
            set {
                this.nodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool multiPhase {
            get {
                return this.multiPhaseField;
            }
            set {
                this.multiPhaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Bladdermin_XML_Library")]
    public partial class BladderminProtocolConstraintsConstraint {
        
        private string nameField;
        
        private double doseValueField;
        
        private string doseUnitField;
        
        private string volumePresentationField;
        
        private double volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double DoseValue {
            get {
                return this.doseValueField;
            }
            set {
                this.doseValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DoseUnit {
            get {
                return this.doseUnitField;
            }
            set {
                this.doseUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VolumePresentation {
            get {
                return this.volumePresentationField;
            }
            set {
                this.volumePresentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
    }
}
